# Generated by Django 4.2.8 on 2025-12-23 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('company_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('status_changed', 'Status Changed'), ('timeline_updated', 'Timeline Updated'), ('priority_updated', 'Priority Updated'), ('comment_added', 'Comment Added')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_task_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('related_task_title', models.CharField(blank=True, max_length=255, null=True)),
                ('triggered_by', models.UUIDField(blank=True, null=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user_id', 'read'], name='notificatio_user_id_1f75db_idx'), models.Index(fields=['company_id', '-created_at'], name='notificatio_company_004504_idx')],
            },
        ),
    ]
