# Generated by Django 4.2.8 on 2025-12-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='taskchecklist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'managed': False, 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='taskintegrationsettings',
            options={'managed': True, 'verbose_name_plural': 'Task Integration Settings'},
        ),
    ]
