# Generated by Django 4.2.8 on 2025-12-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='taskchecklist',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='taskintegrationsettings',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_company_b08c22_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_company_dc9252_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_assigne_6ebd4c_idx',
        ),
        migrations.RenameField(
            model_name='taskcomment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_department_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_cross_department',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_redirected_to_team_lead',
        ),
        migrations.RemoveField(
            model_name='task',
            name='team_lead_approval_pending',
        ),
        migrations.RemoveField(
            model_name='task',
            name='team_lead_id',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='company_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='task_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='order_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='task_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='mentions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='task_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskintegrationsettings',
            name='allow_employee_task_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskintegrationsettings',
            name='allow_employee_task_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskintegrationsettings',
            name='allow_timeline_priority_editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskintegrationsettings',
            name='company_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='taskintegrationsettings',
            name='cross_department_task_redirection',
            field=models.CharField(choices=[('none', 'None'), ('team_lead', 'Team Lead'), ('department_head', 'Department Head')], default='none', max_length=20),
        ),
    ]
