# Generated by Django 4.2.8 on 2025-12-08 07:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='Timezone for the company', max_length=50)),
                ('currency', models.CharField(default='INR', help_text='Currency code (e.g., INR, USD)', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_plan', models.CharField(blank=True, choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=50, null=True)),
                ('subscription_valid_until', models.DateField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending - Awaiting Admin Creation'), ('admin_created', 'Admin Created - Setup in Progress'), ('setup_complete', 'Setup Complete')], default='pending', max_length=20)),
                ('setup_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('setup_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_setup_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('personal_email', models.EmailField(max_length=254)),
                ('temp_company_email', models.EmailField(max_length=254)),
                ('temp_password', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_tokens', to='companies.company')),
            ],
            options={
                'db_table': 'company_registration_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_email', models.EmailField(help_text='Real personal email where credentials are sent', max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('temp_password_set', models.BooleanField(default=True, help_text='Whether admin is using temporary password')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Admin',
                'verbose_name_plural': 'Company Admins',
                'db_table': 'company_admins',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companies_name_c7a1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='companies_is_acti_e9a12b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['code'], name='companies_code_3c8feb_idx'),
        ),
    ]
