# Generated by Django 4.2.8 on 2025-12-22 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyshift_remove_companyadmin_company_industry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyshift',
            options={'managed': False, 'ordering': ['start_time', 'name'], 'verbose_name': 'Company Shift', 'verbose_name_plural': 'Company Shifts'},
        ),
    ]
